apiVersion: v1
kind: Pod
metadata:
  annotations:
    apps.kruise.io/runtime-containers-meta: '{"containers":[{"name":"kvrocks","containerID":"docker://292bbc8823b96273af5dacd9ef4b5cf9066b72cd7961efcbe093078d59ceefa2","restartCount":0,"hashes":{"plainHash":109376058,"extractedEnvFromMetadataHash":86995377}},{"name":"kvrocks-exporter","containerID":"docker://88e21d1b24038710b050242f9135d229042c7aa053f0ec938861156057826122","restartCount":0,"hashes":{"plainHash":2875340509,"extractedEnvFromMetadataHash":86995377}}]}'
    lifecycle.apps.kruise.io/timestamp: "2023-07-13T13:17:28Z"
  creationTimestamp: "2023-07-13T13:17:28Z"
  generateName: kvrocks-standard-1-demo-
  labels:
    app.kubernetes.io/kind: KVRocks
    controller-revision-hash: kvrocks-standard-1-demo-68f6d5bcb6
    kvrocks/monitored-by: sentinel-1
    kvrocks/name: kvrocks-standard-1-demo
    kvrocks/role: master
    kvrocks/statefulset: kvrocks-standard-1-demo
    kvrocks/system: gt
    lifecycle.apps.kruise.io/state: Normal
    statefulset.kubernetes.io/pod-name: kvrocks-standard-1-demo-0
  name: kvrocks-standard-1-demo-0
  namespace: kvrocks
  ownerReferences:
  - apiVersion: apps.kruise.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: kvrocks-standard-1-demo
    uid: 2e7f47fa-bb96-4209-99ec-b38dcda5b488
  resourceVersion: "1901"
  uid: e1236976-e6c9-4cba-b510-56ede6761a32
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/kind: KVRocks
              kvrocks/monitored-by: sentinel-1
              kvrocks/name: kvrocks-standard-1-demo
              kvrocks/statefulset: kvrocks-standard-1-demo
              kvrocks/system: gt
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - command:
    - sh
    - /conf/start.sh
    image: apache/kvrocks:nightly
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - sh
        - /conf/readiness_probe.sh
      failureThreshold: 6
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: kvrocks
    ports:
    - containerPort: 6379
      name: kvrocks
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - sh
        - /conf/readiness_probe.sh
      failureThreshold: 6
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 100m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /conf
      name: conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p4gvs
      readOnly: true
  - args:
    - --kvrocks.addr=kvrocks://localhost:6379
    - --kvrocks.password=123456
    image: jinxu95/kvrocks_exporter:latest
    imagePullPolicy: Always
    name: kvrocks-exporter
    ports:
    - containerPort: 9121
      name: exporter
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p4gvs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: kvrocks-standard-1-demo-0
  nodeName: e2e-test
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  readinessGates:
  - conditionType: InPlaceUpdateReady
  - conditionType: KruisePodReady
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 20
  tolerations:
  - effect: NoSchedule
    key: kvrocks
    operator: Exists
  - effect: NoSchedule
    key: node
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-kvrocks-standard-1-demo-0
  - configMap:
      defaultMode: 420
      name: kvrocks-standard-1-demo
    name: conf
  - name: kube-api-access-p4gvs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-13T13:17:28Z"
    status: "True"
    type: KruisePodReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-13T13:17:28Z"
    status: "True"
    type: InPlaceUpdateReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-13T13:17:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-07-13T13:17:58Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-07-13T13:17:58Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-13T13:17:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://292bbc8823b96273af5dacd9ef4b5cf9066b72cd7961efcbe093078d59ceefa2
    image: apache/kvrocks:nightly
    imageID: docker-pullable://apache/kvrocks@sha256:b23e82a59f2c09753c2fc0ca240d6060874264762cb752c5897c1433260bde5c
    lastState: {}
    name: kvrocks
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-07-13T13:17:36Z"
  - containerID: docker://88e21d1b24038710b050242f9135d229042c7aa053f0ec938861156057826122
    image: jinxu95/kvrocks_exporter:latest
    imageID: docker-pullable://jinxu95/kvrocks_exporter@sha256:01bf2c7f033c51d9eb7730937aba6c633bb7c6120ff32927a0e8dddf0044a5e8
    lastState: {}
    name: kvrocks-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-07-13T13:17:45Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 172.17.0.10
  podIPs:
  - ip: 172.17.0.10
  qosClass: Burstable
  startTime: "2023-07-13T13:17:28Z"
