# permissions for end users to view kvrocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kvrocks-viewer-role
rules:
- apiGroups:
  - apache.org
  resources:
  - kvrocks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apache.org
  resources:
  - kvrocks/status
  verbs:
  - get
