# permissions for end users to edit kvrocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kvrocks-editor-role
rules:
- apiGroups:
  - apache.org
  resources:
  - kvrocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apache.org
  resources:
  - kvrocks/status
  verbs:
  - get
