//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRocks) DeepCopyInto(out *KVRocks) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRocks.
func (in *KVRocks) DeepCopy() *KVRocks {
	if in == nil {
		return nil
	}
	out := new(KVRocks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVRocks) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRocksList) DeepCopyInto(out *KVRocksList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KVRocks, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRocksList.
func (in *KVRocksList) DeepCopy() *KVRocksList {
	if in == nil {
		return nil
	}
	out := new(KVRocksList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVRocksList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRocksShrinkMsg) DeepCopyInto(out *KVRocksShrinkMsg) {
	*out = *in
	if in.Partition != nil {
		in, out := &in.Partition, &out.Partition
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ReserveMsg != nil {
		in, out := &in.ReserveMsg, &out.ReserveMsg
		*out = make(map[string][]int, len(*in))
		for key, val := range *in {
			var outVal []int
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]int, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRocksShrinkMsg.
func (in *KVRocksShrinkMsg) DeepCopy() *KVRocksShrinkMsg {
	if in == nil {
		return nil
	}
	out := new(KVRocksShrinkMsg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRocksSpec) DeepCopyInto(out *KVRocksSpec) {
	*out = *in
	if in.KVRocksConfig != nil {
		in, out := &in.KVRocksConfig, &out.KVRocksConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Toleration != nil {
		in, out := &in.Toleration, &out.Toleration
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(KVRocksStorage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRocksSpec.
func (in *KVRocksSpec) DeepCopy() *KVRocksSpec {
	if in == nil {
		return nil
	}
	out := new(KVRocksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRocksStatus) DeepCopyInto(out *KVRocksStatus) {
	*out = *in
	if in.Topo != nil {
		in, out := &in.Topo, &out.Topo
		*out = make([]KVRocksTopoPartitions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Shrink != nil {
		in, out := &in.Shrink, &out.Shrink
		*out = new(KVRocksShrinkMsg)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRocksStatus.
func (in *KVRocksStatus) DeepCopy() *KVRocksStatus {
	if in == nil {
		return nil
	}
	out := new(KVRocksStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRocksStorage) DeepCopyInto(out *KVRocksStorage) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRocksStorage.
func (in *KVRocksStorage) DeepCopy() *KVRocksStorage {
	if in == nil {
		return nil
	}
	out := new(KVRocksStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRocksTopoPartitions) DeepCopyInto(out *KVRocksTopoPartitions) {
	*out = *in
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]KVRocksTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRocksTopoPartitions.
func (in *KVRocksTopoPartitions) DeepCopy() *KVRocksTopoPartitions {
	if in == nil {
		return nil
	}
	out := new(KVRocksTopoPartitions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRocksTopology) DeepCopyInto(out *KVRocksTopology) {
	*out = *in
	if in.Slots != nil {
		in, out := &in.Slots, &out.Slots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = make([]MigrateMsg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRocksTopology.
func (in *KVRocksTopology) DeepCopy() *KVRocksTopology {
	if in == nil {
		return nil
	}
	out := new(KVRocksTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrateMsg) DeepCopyInto(out *MigrateMsg) {
	*out = *in
	if in.Slots != nil {
		in, out := &in.Slots, &out.Slots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrateMsg.
func (in *MigrateMsg) DeepCopy() *MigrateMsg {
	if in == nil {
		return nil
	}
	out := new(MigrateMsg)
	in.DeepCopyInto(out)
	return out
}
