apiVersion: kvrocks.apache.org/v1alpha1
kind: KVRocks
metadata:
  name: kvrocks-cluster-1-demo
  namespace: default
  labels:
    kvrocks/monitored-by: sentinel-1
spec:
  image: apache/kvrocks:2.5.1 # kvrocks image
  imagePullPolicy: IfNotPresent
  master: 3
  replicas: 2
  type: cluster
  password: "123456"
  kvrocksConfig:
    bind: "0.0.0.0"
    port: "6379"
    timeout: "0" # 客户端空闲 N 秒后关闭连接 （0 禁用）
    workers: "8"
    daemonize: "no"
    maxclients: "10000"
    db-name: "change.me.db"
    slave-read-only: "yes"
    slave-priority: "100"
    tcp-backlog: "512"
    slave-serve-stale-data: "yes"
    slave-empty-db-before-fullsync: "no"
    purge-backup-on-fullsync: "no"
    max-io-mb: "500"
    max-db-size: "0"
    max-backup-to-keep: "1"
    max-backup-keep-hours: "24"
    slowlog-log-slower-than: "200000"
    profiling-sample-ratio: "0"
    profiling-sample-record-max-len: "256"
    profiling-sample-record-threshold-ms: "100"
    supervised: "no"
    auto-resize-block-and-sst: "yes"
    rocksdb.compression: "no"
    rocksdb.wal_ttl_seconds: "0"
    rocksdb.wal_size_limit_mb: "0"
  storage:
    size: 200Mi
    class: standard # storage class
#  nodeSelector:
#    role: kvrocks
  toleration:
    - key: kvrocks
      effect: NoSchedule
      operator: Exists
    - key: node
      effect: NoSchedule
      operator: Exists
  resources:
    limits:
      cpu: 2
      memory: 8Gi
    requests:
      cpu: 200m
      memory: 200Mi
