name: helm-lint

on:
  push:
    branches:
    - unstable
  pull_request:
    branches: [ unstable ]

jobs:
  lint-test-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.5.0

      - name: Run chart-testing (lint)
        run: ct lint --all --chart-dirs deploy/ --validate-maintainers=false